### ISSUE TITLE
Add save/cancel button for Org Unit assignment

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/dataset-configuration-blessed#100]
## dhis2

- Username: Troyel.Nerbo
## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
- Platform: Win32
## User report
URL: http://dev.eyeseetea.com:8080/api/apps/dataset-configuration-dhis2-app%20(1)/index.html#/datasets?_k=6rqhn5

Could we implement a  "save" and "cancel" button here instead of just "Close"? Thanks! 

![screenshot](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1515404880830222300.png)

**Comment by adrianq** [comment]
Yes, it can be done for Organisation Units but it would be almost impossible to do it for the sharings. We will implement this for the Org Unit assignment
