### ISSUE TITLE
Hide data elements from app selection

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#101]
Hi,
Can we have a functionality to mark some data elements / indicators as not possible to assign through the app. Alternatively that it is only possible to add for someone with a particualr right/group.

The reason for this is that we want to have separate data sets for the indicators GL-X1 and GL-X3 (and potentially GL-X2). Because these should never be reported on the same attribute combination as the other indicators/DE. Please suggest some good ways of doing this

**Comment by adrianq** [comment]
We can just add an attribute (yes/no) for this. Depending on this attribute we will hide/display the DE/Indicator on the app. How does it sound?

**Comment by troyel** [comment]
Yes - makes sense!

**Comment by adrianq** [comment]
Great! Are you taking care of this? If so can you send us another dump? It would be great if you can also solve these two https://github.com/EyeSeeTea/dataset-configuration-blessed/issues/91 and https://github.com/EyeSeeTea/dataset-configuration-blessed/issues/81

**Comment by troyel** [comment]
Does a "Yes only" attribute work?
![hide in DS app attribute.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46e09d9e26c28aa7cfcd8c03a54de0d4285233612006b63f75c7af6aaf50740b0a0c0abe4b4a5a4caffc817af0b13521db5a0bbcd16d5d27c43940a8bc830da313f871d51bdaebe5c01982fa3737e68c854e3b1f001d89fe5836a8904cc14abb.PNG)

**Comment by adrianq** [comment]
Yes, it does!
