### ISSUE TITLE
Autoforms created outside app how to show section headers?

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#102]
Hi,
So we probably want to have the option to create forms outside the app as well. I created one with section names and it seems they are hidden by the javascript. Any way I can get it to show without too much changes?

![form section headers.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46ee9b882ec290ac8cfdb64caa1df891284222613a46ef696097ec22ba416f43554d4ba4125d5715aafe807af7b03c218a5c09bed3690e70c23c03b0aac04ee155e57dd205d0f4ae805ec1e03724e28a8a4b3e19071d8dfd5c31b2d4.PNG)

**Comment by troyel** [comment]
BTW. The picture above was taken on a non-ingocnito mode where the proper JS isn't applied.

**Comment by adrianq** [comment]
Ok, we have identified the problem for this. In the mid-term, it may be interested to use a dataset attribute to identify datasets created by the Dataset Configuration app
