### ISSUE TITLE
Slow loading/drawing of forms

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#103]
Implemented attribute "Group" on the output data elements now and it considerably slows down the loading/drawing of the form. Just the outputs now takes about 20 seconds to load on fast laptops. Any way we can look to speed this up? Haven't tested with outcomes yet but it's likely not to help..

Test on:
![slow loading test.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46fb989534c28fa68eedb64da31de4913a52653f6b14b1247a80e03cfd183954570c4ba4100e584dada88f2bf7b63c72d95e0fbcd5695e66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3c20e38989473c18041c80ed10.PNG)

**Comment by adrianq** [comment]
This is a tricky one. We are currently processing a lot of stuff, in particular, splitting several tables depending on the screen width. We will have to look into it and try to improve the performance. Will keep you posted!
