### ISSUE TITLE
default disaggregation without header

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#104]
Could we put in a column header "Value" or something on the disaggregations on "default"? Easy to miss these without.

![default dissagg wo header.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46ec919c22978fbdcfedb650b75cf793695128332101a22f7597a164fd52690e050a1de853524d41f4aa8c23f7e03b79db0d0ded806d5f76953f15fdbc861ead1da862da11d1e9e1d30695aa2f2ff58a87453f1b041d8dfd5b3ca59148c95ce406.PNG)

**Comment by adrianq** [comment]
Yes, no problem. We got rid of the value because it was a bit redundant in some cases but we will have a look at it and re-add it for the default disaggregation

**Comment by troyel** [comment]
Great!
