### ISSUE TITLE
"Data element decorations"

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#106]
When the "Data Element Decoration" setting is marked in the data set - Vanilla DHIS let you see the definition(description) of the data element by hovering over the DE description. As far as I can see this doesn't seem to work when the custom JS is applied? Did a test on vanilla data set and compared to one on the app server.

Vanilla example:
![vanilla data element decoration.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46fe95942a8e8fa8cfedbe57a51df5982c4b227d3d44a72e738af129ab4b740f4d435cec03070511afbd9b21b4b334238f545abbd6640e25c03d40acb8804cbd05eb248f4e97aaaec81d9ebc6278bec1da0d2c1417198ef55c30a19c4fc151f248e74c54a0017b.PNG)

**Comment by tokland** [comment]
Fixed (already on dev, since it's custom JS code, it needs no release).
