### ISSUE TITLE
Missing authority to access dataset-configuration

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dataset-configuration-blessed#107]
(Current imported DB: 20180110T032602Z)

For example, user Ne...Gh... gets a 403 when she tries to access dataset configuration. All users with rights to access dataset-configuration should have the authority "See Dataset configuration" through some user role. 

@troyel, which user role is the most convenient for this? for now, I've added it to "GL_Basic_User"

**Comment by troyel** [comment]
Aha. Yes I think we will create a new user role for this.
I haven't updated yet but new role will be:

Name:
GL_DataSetConfiguratorApp_role
ID:
YcKWnELyQd6
