### ISSUE TITLE
User rights for role

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dataset-configuration-blessed#108]
(Current imported DB: 20180110T032602Z)

User Ne...Gh... trying to create a dataset associated with project JOFM1608 and Core competencies education / camp management results in errors messages:

- User `Negar Ghobadi [RZmzKVc9ToB] (User)` is not allowed to update object `JO__dataset_education [lo7nrPmQ32N] (UserAuthorityGroup)

- User `Negar Ghobadi [RZmzKVc9ToB] (User)` is not allowed to update object `JOFM1608 (BPRM) [JYBFrPqDMbp] (DataElementCategoryOption)

This can be solved by adding the user to some group that provides rw rights (i.e. MERO_Administrators - [update] JO_Administrator is read-only), this way it can now update the role and project. @troyel, can you confirm which is the correct rights for this kind of users?

**Comment by troyel** [comment]
Negar should be in JO_Administrators. I'm surprised this is still an issue as `JO__dataset_education  is shared with read access (does it need rw?). And All project codes are shared with rw to JO_Administrators...

**Comment by tokland** [comment]
Yes, to update a user role you need rw (JO_Administrator is only read, sorry)

**Comment by tokland** [comment]
We are closing this, updated details on email.
