### ISSUE TITLE
Add logs mechanism

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#113]

**Comment by ardhimanshu** [comment]
Great that you had logs mechanism implemented (as you showed during the workshop). There is another issue which talks about "paging in logs as the logs could grow quite long". As long as we can scroll through the whole log, paging is not a priority...

**Comment by adrianq** [comment]
Yes, by 'paging' I meant we need to store the information on the server as pages. After a few weeks working with the app we are gonna have hundreds/thousands of logs and we don't want to download so much information because it is gonna slow down the app. Instead, we will download just the first page (100 records) and then when the user scroll down or press a button we will download and display the second page and so on... This way it is more scalable and provides a better user experience. This is almost done and will be released as part of the next version
