### ISSUE TITLE
Add title or background color in the landing page

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#121]

**Comment by adrianq** [comment]
We finally changed the background color and displayed a message in the Dhis2 header. Also, we added an informative message on the app subheader regarding the action is taking place 'Create...' , 'Cloning ..', etc.

**Comment by ardhimanshu** [comment]
Not sure if you are talking about a specific background color and message. What I see is black strip at the top which has "Global Ouput and Outcome Reporting
 - Dataset Configuration" written on it. I see "Create" when moving ahead during process of 
 dataset creation. Where are we supposed to see "cloning"?

**Comment by adrianq** [comment]
Let me clarify what this issue is about.

First the main header:
![screenshot from 2018-03-15 15-48-01](https://user-images.githubusercontent.com/6850223/37474523-714d1ce6-2868-11e8-8d21-eda2cb0e4424.png)

It has a different colour than the rest of the Dhis2 apps. It also contains a message '- Dataset Configuration' that is not in any other app. As we discussed, the purpose of this is to clearly identify when you are in the NRC Dataset Configuration app so that users don't get confused and think they are in the regular maintenance app.

The subheader. It will display a different message depending on what action the user is performing.
If I click on the + button and start creating a dataset:
![screenshot from 2018-03-15 15-55-50](https://user-images.githubusercontent.com/6850223/37474934-6d70cfcc-2869-11e8-85e4-c874f0f87434.png)

If I right-click on an existing dataset and choose to edit the dataset:
![screenshot from 2018-03-15 15-59-03](https://user-images.githubusercontent.com/6850223/37475133-df871904-2869-11e8-82d7-1859f6c17506.png)

If I right-click on an existing dataset and choose to clone the dataset:
![screenshot from 2018-03-15 15-59-32](https://user-images.githubusercontent.com/6850223/37475151-e9955c9e-2869-11e8-802c-bbb31830e427.png)

Hope it is clear now...

**Comment by ardhimanshu** [comment]
OK! Cool!
