### ISSUE TITLE
Problem with filtering in "Sections" Tab

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#127]
While creating dataset, as we reach the "Sections" tab, and we try to filter by "Group", "Origin", "Selected", it shows "item.txt" in the list. It seems to be a new issue (didn't exist earlier) which probably came up while fixing something else.

**Comment by ardhimanshu** [comment]
Image attached for reference.
![DC_App_SectionTab_Filtering_Error_Screenshot.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a82a9ba56ec00001202c168/125516c66e82c728ace21e0d46ccb7a502929396bcecbc57ad52fea0284418552008b72e628ced2f80676913001d21cf121a0a11a2bad174e2a42062ca1e54b7843e1b66cc2f14a4eb8717ee57bd29da1e83b6ed8a4cc2bb3f21b68f8b4e2c02175ad8a1096afdc0019d1ae441f34c5cae123361e777347f479c19712b6d756b.PNG)

**Comment by adrianq** [comment]
You are right, this is a bug and I have been able to reproduce it on our dev server. We will have a look at it and come back with a solution for the next release. Thanks!

**Comment by ardhimanshu** [comment]
Can you tackle this as a priority please? We are planning to launch very soon. Thanks.

**Comment by adrianq** [comment]
No problem. We can release a new version very soon but before releasing... did you find any other bug during the pilot you want to include as part of this minor release? any minor improvement? The releasing process takes some time and if you (or Erika) have anything else in mind I prefer to implement it for this release as well.

**Comment by ardhimanshu** [comment]
So far not. But will confirm by Monday.

**Comment by ardhimanshu** [comment]
Added an "enhancement" request in "Ready" section.
