### ISSUE TITLE
Send internal Dhis2 message using feedback tool instead of opening a waffle card

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#130]
Message should be sent to GL_SysAdmin  or GL_M&E user group.

**Comment by adrianq** [comment]
@ardhimanshu can you specify what user group we should use for the feedback tool?

**Comment by tokland** [comment]
Note that `GL_SysAdmin` is a user role, not a group, it cannot be used for that. Although the `GL_M&E` user group was in the specifications, it was never created on GORS  instances.

Existing global/admin groups (from gors.nrc.no), if that helps: `GL_AllAdmins`, `GL_GlobalAdministrator`, `GL_LocalindicatorAdmin`, `GL_UserAdmin`.

**Comment by ardhimanshu** [comment]
Feedback can be sent to GL_GlobalAdministrator, GL_LocalindicatorAdmin for now.

**Comment by tokland** [comment]
Ok!

**Comment by ardhimanshu** [comment]
We tested the feedback feature again as a local Iran user. It gives the error )see attached screenshot) and doesn't send the message.
![Feedback_feature_new_issue.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a82a9ba56ec00001202c168/125516c66e82c728ace21e0d46ce919f278082aa84d6b946a549e5862c7929763e3baa386390e66af3006b1300051bff054a5556f9f1da2eaee76a77830d5aebd13c5f74c46e13a8e9861bbe13a632c91edbe2e3d7158abd7f37ed998e46341f001a8dfa5b33a4914bcb59f759ac.png)

**Comment by adrianq** [comment]
@ardhimanshu I have seen this error only once and it was due to a timeout for inactivity. Could that be the case? Can you please let me know the username so I can try to replicate this issue as well?
