### ISSUE TITLE
Dataset to automatically be named as "ProjectName DataSet"

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#131]
While creating dataset, in first step we select a project and Core competencies. In next step, we give name to the dataset being created. Automatically, the project name is assigned as Dataset name. It allows us to edit this (we decided to append the term "dataset" after the name assigned by default. Is it possible that the term "DataSet" is automatically included as part of the given dataset name (instead of it just being project name)? This will help reduce confusion for our users in the future.

**Comment by tokland** [comment]
Yes, it could be done, and would have help prevent what happened in #132 

Question: Given the typical name of the project (spaces, no underscores), wouldn't it be better to use `ProjectName DataSet` instead of `ProjectName_DataSet`?

**Comment by ardhimanshu** [comment]
Right - we do not have control on Project ids (we could modify with underscores in our systems) but it could create additional work when matching them with project ids in other systems. So yes - for consistency purposes, we can do away with the underscore and put the term "DataSet" at the end of the Project name separated by single space and not underscore.
