### ISSUE TITLE
Problem with new org units

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/dataset-configuration-blessed#136]
## dhis2

- Username: Patrick.Akena
## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
- Platform: Win32
## User report
URL: https://gors.nrc.no/api/apps/dataset-configuration+(2)/index.html#/datasets/add?_k=0jjnp6

I have new organization units (Palorinya_AO and Kyangwali_AO) in my country office(Uganda) this year which are not showed.How do I include them?

![screenshot](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1523613808373711823.png)

**Comment by adrianq** [comment]
@ardhimanshu I have assigned this to you as it has to do with the GORS metadata. Let me know if you need anything on our side

**Comment by ErikaMichelet** [comment]
Done
