### ISSUE TITLE
Dates available to enter Target data

### ISSUE THREAD

**Issue by ErikaMichelet** [EyeSeeTea/dataset-configuration-blessed#140]
DC app allows entering data for the current month. Country offices need to enter beforehand target info for the full project period (end 2018, 2019, in some cases up to 2021.

**Comment by tokland** [comment]
I've checked the periods added to the dataset and they look correct, from the start to the end of the project.

Do you perhaps mean the values of the period selector in dhis-web-dataentry? The limit there is determined by the field "Open future periods for data entry" (currentDate + _openFuturePeriods_ months).

**Comment by adrianq** [comment]
As agreed, new version will calculate and set openFuturePeriods until the end of project.
