### ISSUE TITLE
Not able to see dataset in data entry form

### ISSUE THREAD

**Issue by ErikaMichelet** [EyeSeeTea/dataset-configuration-blessed#150]
The user can create datasets but not view them in data entry form (only one dataset is visible).
User: TKilunda
Password: ****

I tried to work on the sharing settings of dataset and project to match the groups he belongs to and it didn't work.
I talked about him before... could you please have a look and solve this issue?
Many thanks
Erika

**Comment by tokland** [comment]
Sorry for the delay, Erika. I've logged-in with user TKilunda and I see 3 (not 1) datasets available using any of the 4 organization units. For example:

![screenshot from 2018-07-26 12-42-54](https://user-images.githubusercontent.com/24643/43258062-c6c1e6c6-90d1-11e8-9376-b93254dd1482.png)

Can you tell me the name of the dataset(s) that you expect to see there but don't appear?

**Comment by ErikaMichelet** [comment]
The datasets he should see are all those created with the DC app and starting by KEFM
KEFM1612
KEFM1719
KEFM1728
KEFM1801
KEFM1802
KEFM1807
KEFM1810
Thank you

**Comment by tokland** [comment]
It seems to be ok. Datasets are linked to certain orgUnits only. 

Let's see an example: Dataset "KEFM 1612":

https://SERVER/dhis-web-maintenance/#/edit/dataSetSection/dataSet/Q4wogeIKSyS

We check which orgunits the dataset is linked to:

![screenshot from 2018-08-08 12-10-47](https://user-images.githubusercontent.com/24643/43831430-63bf6976-9b04-11e8-98f3-0f10089b59fb.png)

And now let's check the available datasets for that orgUnit, expected dataset are shown:

![screenshot from 2018-08-08 12-09-24](https://user-images.githubusercontent.com/24643/43831541-c4d02ade-9b04-11e8-9efa-b3a8d4432132.png)

**Comment by ErikaMichelet** [comment]
Funny... Before I could not see it, even using the correct location.
The important part is that it is solved. Thank you.

**Comment by tokland** [comment]
Erika, when checking this issue I noticed something: Remember that users that can create datasets should have rights to add those datasets to the corresponding user roles. For example, if a new dataset for country KE has core competency education, this new dataset will be added to user role "ke__dataset_education". That's only possible if the user has write-access to the user role.

TKilunda belongs to group KE_Administrator, but this group has read-only access to KE__dataset_xyz user roles:

https://gors.nrc.no/dhis-web-maintenance-user/allRole.action?currentPage=1&key=ke__dataset_education

(-> Sharing settings)
