### ISSUE TITLE
User group

### ISSUE THREAD

**Issue by ErikaMichelet** [EyeSeeTea/dataset-configuration-blessed#152]
What is the user group for CC OTHER? Do I have to create a user group CountryName_OTHERUser ?

**Comment by tokland** [comment]
Yes, as far as I can see, it does make sense to create user groups or the `Other` core competency, as we have for the rest. It's not used by dataset-configuration in any way, but you may use to control sharing access.

Note that, following the current conventions, it should be (ex: Afghanistan): `AF_otherUsers`:

https://latestgors.nrc.no/dhis-web-maintenance-user/getAllUserGroups.action?key=users&curKey=af_
