### ISSUE TITLE
Filter function is not working

### ISSUE THREAD

**Issue by ErikaMichelet** [EyeSeeTea/dataset-configuration-blessed#153]
If I search a dataset with the checkbox "only created by the app" checked, the filter do not work

**Comment by ErikaMichelet** [comment]
![FIlter by dataset name dont work.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5af97232f4ddc900131b5a5d/125516c66e82c728ace21e0d46cebd96378791e98df0ff47a549f1872c52677d2809a66b748aed3cff557413044d52be011a001ea9aacd39aca43978d95903bc876a5625973b11fdb8821dec03be718f4b84a4a0980e91b6697abad2c51a7c0c0f0a8bfe5734a59a4ccb5dfe42e04d54a512242e.JPG)

**Comment by tokland** [comment]
Indeed, the search filter is not working when checkbox is set. Issue opened, will be fixed shortly.
