### ISSUE TITLE
Rules for sharing settings

### ISSUE THREAD

**Issue by ErikaMichelet** [EyeSeeTea/dataset-configuration-blessed#155]
The rules for the sharing settings are too complicated (and I finish by spending some hours fixing the metadata (category option and dataset sharing settings).
Can we simplify it?
Can we have the sharing settings coming directly from the CCs and location in the dataset?

**Comment by adrianq** [comment]
I am attaching the diagram that we use for today's meeting.
![Untitled Diagram.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/537c7e24ebef97b1f959e61a/125516c66e82c728ace21e0d46dd9a8e2a968fac8ba99b4aa55ae29524046b313916ac217586f76ae5002e590c5a46fd175f5615adff897aa6b63e2388585ae9d56c4d68d47f40f2ecdd42e64bef62994597b7b4804dc5ec3c20e78a894d371f071b9bb2.png)

I am also assigning this card to you as we discussed...
