### ISSUE TITLE
Wrong data in analytics

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#157]
Wrong data in analytics due to duplicated uids for dataelement/indicators:

indicator_uids="XMRmqF9reP5 UzT7DSkkbxH ZDONOAJJNBV wFrRdK9XyIM"

We will prepare a SQL script to fix this problem

See https://github.com/EyeSeeTea/dataset-configuration-blessed/issues/149 for further information

**Comment by tokland** [comment]
I've executed the fixing script in dev.est. This favorite had one column working, the other with a duplicated indicator. Now both are ok:

http://dev.eyeseetea.com:8080/dhis-web-pivot/?id=VtFXu8XsWoV
