### ISSUE TITLE
Close a single section or the whole Dataset

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#159]
- [ ] New piece of metadata -> Dataset attribute 'Dataset State' with three options: Open/Close Output/Close Output&Outcome. We will pass NRC the JSON file to include this new piece of metadata in their GORS server.
- [ ] Two new pieces of metadata ->  Dataset Close Output Date and Dataset Close Outcome Date
- [ ] A contextual option will be added to Close/Open datasets ( for single and bulk actions). If the user chooses to ‘Close Outputs’ Output sections will be disabled in data entry while if the user chooses to ‘Close Output&Outcome’ the whole dataset will be disabled. On the other hand, if the dataset remains ‘Open’ it will work as usual.
- [ ] Only certain users can close a dataset. NRC to provide who (See https://waffle.io/EyeSeeTea/dataset-configuration-blessed/cards/5c792ab5144d8f024b94a8a1)
- [ ] Modify save to set this attribute as Open

**Comment by adrianq** [comment]
See proposal https://docs.google.com/document/d/1F3yrhGjpay-BgbajI7QeImFEG2lekHn5sxu-ssNGeCw/edit
