### ISSUE TITLE
Provide user, user group or role that are allow to close a dataset

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#164]

**Comment by ardhimanshu** [comment]
Here we need to make a distinction - The dataset creators (e.g., at Country level) should not be able to modify dates for closing of data entry (for output and outcome) for a given year in a project. Only a power user (e.g., global admin) should be allowed to modify such dates.

**Comment by ardhimanshu** [comment]
Is this point clear and will it be included in the next release?
