### ISSUE TITLE
Allows creation of datasets with same name

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#166]
The app allows user to create datasets with same name. That can create confusion among users. So the app, during naming, should first check from list of already existing names and should trow an error if the name already exists.

**Comment by adrianq** [comment]
OK, we are currently performing the same validation DHIS2 does, i.e. 'name' can be duplicated while 'code' needs to be unique. Anyway, I understand your point here. We will enforce uniqueness for the name and check if there is any duplicated dataset at the moment.
