### ISSUE TITLE
Data Entry form structure

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#169]
Naturally some indicator and data element names are longer than others. This means that in data entry form, user needs to scroll to the right to reach the value entry box. This gives rise to possibility of user entering relevant value in box for another data element or even comment box. Can There be a possibility of, for example, text wrap and possibly indent adjustating for boxes and names so that the data entry forms are consistent across different screen sizes. Lower priority.

**Comment by adrianq** [comment]
This layout customizations are not particularly easy to do it. We will have a look at it and let you know how feasible it is...
