### ISSUE TITLE
Data Entry form completion (Question)

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#170]
Some issues have come up with regards to data entry forms and I am not sure if it is related to the dataset configuration app or something else. The issue is: Upon entering data in a given cell (box), the user assumes that data is auto-saved when the cell turns green. However, it does not seem to get saved. Also in some cases, the cell does not even become green. Could it be related to the app or our configuration and any suggestions on how to sort this issue.

**Comment by adrianq** [comment]
@ardhimanshu A bit difficult to know with so little information. Have you identified any particular dataset that is causing this problem? In principle, there hasn't been any change in the app that can introduce this bug. Maybe something related to the open and close date of the Organisation Unit? Just guessing...
