### ISSUE TITLE
Editing and saving particular dataset by "particular user" gives error

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#171]
#HighPriority: Editing and saving particular dataset by "particular user" gives error. User Thomas Kilunda. When the user tries to edit and save a dataset again, it gives him error message. Message attached.

**Comment by ardhimanshu** [comment]
[ThomasKilundaDataSetSavingError.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a82a9ba56ec00001202c168/125516c66e82c728ace21e0d46dc9c952e83908286e5aa4da05cd4953d4714763d37a23d798be40dad5074134d435cec03070511afbd9b21b4b334238f545abbd6640e25c03d40acb8804cbd05eb248f4e97aaaec81d9ebc6278bec1da0d2c14171980f55c30a59e4ace5af64be54b5da7017b.txt)

**Comment by adrianq** [comment]
@ardhimanshu It has to do with sharing settings as usual.

These are the sharings for a regular dataset:
https://gors.nrc.no/api/sharing?type=dataSet&id=x802DwRKB86
As you can see, sharings usually contains the user groups GL_GlobalAdministrator plus [country]_administrators and [country]_users

However in the one you shared with us the sharing looks like this:
https://gors.nrc.no/api/sharing?type=dataSet&id=edQvobvlQTh
As you can see, in this case, sharings are only set for the user group GL_GlobalAdministrator. Therefore a regular user can not edit it. To fix it, just add the other two groups for the country to the sharings of this dataset.

We are not sure how this happens as the step to choose the country is compulsory unless you select a project. If you choose a project the country is set behind the scenes and it is transparent for the user. In any case, the country should be always set when creating a dataset. If this happens again it would be good to know how the dataset was created (a step-by-step explanation).
