### ISSUE TITLE
Can't delete dataset

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#172]
Can't delete a dataset. It gives error (Attached image). Possibly, I can delete dataset after deleting project?
![dataset_delete_issue](https://user-images.githubusercontent.com/13102424/59358106-465ba780-8d2c-11e9-91e3-0c0a3de2e244.PNG)

**Comment by adrianq** [comment]
Can you send to us the dataset name (or UID) and the server url?

**Comment by ardhimanshu** [comment]
@adrianq Earlier the message used to be: "can't delete object". However, now we get different message. See screenshot attached. When we click "Ok", nothing happens and dataset remains in the list.
![dataset_delete_issue](https://user-images.githubusercontent.com/13102424/62782172-fabe4380-bab9-11e9-895e-955858268cfc.PNG)

**Comment by ardhimanshu** [comment]
This was an example when we tried to delete AFFM1202. NORAD Dataset on gors.nrc.no

**Comment by tokland** [comment]
This is related with the Dhis2 bug that Adrian described in the email on August 8th: cloned data sets are wrongly using the same custom form (`dataEntryForm`). For those data sets, when deleting a data set and its form, the API detects a dependency with another data set and stops the process. Note that the `[OK]` button is just to close the message box, we simply render the response from the server verbatim, there is not much more we can do at this point.

In this case, the other data set linked with the same custom form is *AFFM1202*:

```
$ curl -sS -g -u $AUTH "https://$GORS/api/dataSets.json?filter=dataEntryForm.id:eq:Wd2ATCgjw3C" | jq '.dataSets[] | .displayName' -r
AFFM1202 NORAD DATASET
AFFM1702 NORAD DATASET
```

**Temporal solution**: go to Maintenance App -> Data Set -> search *AFFM1702* -> mouse right-click  ->  *Design data entry form* -> [DELETE] (page bottom) -> [CONFIRM]. Now you should be able to delete the data set from the app (and also AFFM1202, if needed)

**Permanent solution**: we should run the script we prepared to fix the problem with those 60 data sets with shared custom forms.

**Comment by ardhimanshu** [comment]
If we delete the data entry form which is connected to two different datasets, will it anyway affect the dataset (that we want to keep) or data entry for that dataset?

**Comment by tokland** [comment]
No, deleting a custom form has no effect over the data set or its data, it's just the form that is deleted (which only contains the HTML). For our dataset-configuration data sets, this form can be regenerated with a Edit->save. For non-app data sets, you may save the source code somewhere to restore it afterwards, if required.
