### ISSUE TITLE
Error in saving dataset with different date possibilities for output and outcome open close.

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#173]
Error in saving dataset with different date possibilities for output and outcome open close.

**Comment by ardhimanshu** [comment]
![datasetconfig_issue1](https://user-images.githubusercontent.com/13102424/60213162-2d421300-9863-11e9-9772-fa75eb8c37ac.png)

**Comment by adrianq** [comment]
@ardhimanshu For this release to work as expected, you need to create two dataset attributes as I said in my email:

> Find also attached the xml you can use to import the new metadata (two new dataset attributes for datasets).

Did you already do this?

If so, you should see the two attributes when clicking on the app settings:
![image](https://user-images.githubusercontent.com/6850223/60253015-3ebb0780-98c3-11e9-9044-cd6f24e0bc41.png)

**Comment by ardhimanshu** [comment]
@adrianq Ok - thanks. I am wondering if it is important to keep same uids as in xml? I am a bit unsure about posting the xml to dhis2. Can you suggest the posting call for attribute? Otherwise I can create them manually (but the uids won't be the same then).

**Comment by adrianq** [comment]
@ardhimanshu Not sure I completely understand your question... UIDs are not important, in the app we use the attribute code. To import the XML in DHIS2, you need to go in DHIS2 to the 'Import-Export' and then select 'Metadata Import' and fill the fields in the form.

**Comment by ardhimanshu** [comment]
Got it. That issue is solved now but I came across another issue. The open date for a year can start before the close date for previous year. It is good with flexibility so we keep it this way for now.

I was under impression that import/export does not work attributes. Is it so that if the file is in json or xml, we can bulk import any metadata including "indicators", for example? Would be great to know for indicator specifically..(once, for example, one has done bulk upload of numerator and denominator data elements)

**Comment by adrianq** [comment]
This is great news! To implement a validation rule for the start and end date, as you suggested, can be done in case you changed your mind about this.

Import/export feature should work with almost any type of metadata (including indicators) although sometimes could be a bit buggy. You can even mix different type of metadata in the same file.

I am closing this issue now as I think everything has been solved. Feel free to reopen it or create a new one in case you come across a new issue.
