### ISSUE TITLE
Pre-selection of output outcome open close dates and bulk assign options

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#174]
@adrianq Is it possible to have pre-selected output and outcome open and close dates. The open dates, for example, could be beginning of each year (unless project starts sometime during the year) and the output close dates could be 1st April every year and outcome close dates could be 1st May every year. And then can we have a feature which allows us to bulk apply "such data change" for specific selected datasets in list (e.g., now we can bulk apply org units, sharing settings etc.).

**Comment by ardhimanshu** [comment]
@adrianq Just to clear the confusion for version 1.2: There are no pre-selected open and close dates for each year of multi.year project and no bulk date change option. Am I missing something.
![image](https://user-images.githubusercontent.com/13102424/62930677-293f6580-bdbd-11e9-90be-9bbf71be0866.png)

![image](https://user-images.githubusercontent.com/13102424/62930736-45db9d80-bdbd-11e9-8757-621ff628d67f.png)

**Comment by tokland** [comment]
Is that the gors server? I checked there, v1.2 is installed and contextual menu is showing as expected:

![image](https://user-images.githubusercontent.com/24643/62932719-fac38980-bdc0-11e9-9801-50cdcc724284.png)

Check in incognito window to be sure, maybe it's a cache problem. Note that in the step 2 of the wizard, you won't see automatic set of dates until you start or end date.

**Comment by ardhimanshu** [comment]
Thanks! Yes it was the cache issue. Works in incognito.
