### ISSUE TITLE
Issue for Global All Admins at step "Local & Donor Indicators"

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#175]
In the step "Donor and Local Indicators", "Global all admins" can't proceed without selecting at least 1 indicator. They should be able to proceed. It is the "roles other than Global all admins" that should not be allowed to proceed without selecting "at least 1 global mandatory indicators" (not donor and local indicators).

**Comment by ardhimanshu** [comment]
![image](https://user-images.githubusercontent.com/13102424/62295674-e4870680-b46d-11e9-85a1-9d0b04712c91.png)

**Comment by adrianq** [comment]
@ardhimanshu You are right. There was a misunderstanding here. We don't apply validation for "Global all admins" for **Core** Indicators, i.e. the user doesn't have to select a core indicator if he belongs to "Global all admins". However, the user still has to select at least one indicator (either core or donor/local for a core competency). We can for sure do what you want but in our opinion, it is a bit strange. For instance, in your example, you will be creating a dataset with ICLA and Education but no indicator or data element will be selected for Education and therefore the tabs on the form will look empty. Are you sure this is what you want?

**Comment by ardhimanshu** [comment]
@adrianq  I see - somehow I misunderstood it as not allowing Global admin to move forward only if they have not selected any local indicator. However, still, for global admin, can this flexibility exist for global admin? Sometimes we need to test and we can save a bit of time by not having to select more than 1 indicator. However, let's not keep this a priority unless it takes only few minutes for you to implement.
