### ISSUE TITLE
Problem editing old datasets with modified app

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#176]
We have been notified that with the new modifications in the app, there is problem about modifying old datasets. After choosing the org units and clicking next, it doesn't open anything in the step "Core Indicators". It just shows that it is working for long time without showing any list of mandatory indicators.

**Comment by ardhimanshu** [comment]
![somalia_issue_with_editing_old_datasets_with_newApp](https://user-images.githubusercontent.com/13102424/62453419-9413ef80-b772-11e9-8085-a3a2ad781530.png)

**Comment by adrianq** [comment]
@ardhimanshu We cannot reproduce this error. We have tried at GORS with the dataset on your screenshot but it works fine for us. Is it still failing for you? Can you send us another dataset in GORS where you are having this error?

**Comment by adrianq** [comment]
We are thinking it may have to do with the user permissions. I guess you were not using your own user credentials. Is this happening to you? Otherwise, can you send to us the username so we can investigate a bit more this issue?

**Comment by ardhimanshu** [comment]
It has now been reported from two locations - even for creating new datasets> Kennedy.Ndagano (Dataset: CDFM1927 (UNICEF) Dataset) and Mohamed.Hassan (in Somalia - as was attached in original issue)

**Comment by adrianq** [comment]
@ardhimanshu We have been able to reproduce the error. We are now investigating and implementing the fix and will include it in the release. Hopefully, we will be able to release the new version together with this fix by tomorrow. Keep you post it!

**Comment by ardhimanshu** [comment]
@adrianq Any updates? It is urgent as more countries have reported on this now.

**Comment by adrianq** [comment]
@ardhimanshu We have just sent you the new release and a mail explaining the different issues. Note, however, this is not an issue in the app. It has to do with a wrong configuration of the metadata on your side. In particular a wrong configuration of the public access of certain data element groups. You can find more details on the mail I have just sent you.
