### ISSUE TITLE
missing GL_admin group

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#28]

**Comment by adrianq** [comment]
To use GL_GlobalAdmin instead

**Comment by adrianq** [comment]
@troyel We are currently using GL_GlobalAdministrator. Can you double check on your servers if this is the right code?

**Comment by troyel** [comment]
Thats good! 

Name:
GL_GlobalAdministrator

ID:
M9dPUWRdk4L

**Comment by adrianq** [comment]
Great. Closing this then...

cc @tokland
