### ISSUE TITLE
Discuss/Analyse how the data set is presented, as well as printing or downloading form options

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#42]

**Comment by troyel** [comment]
A few things off the bat : 
* hide/remove the "filter dataelement" white input bar that is present and mostly useless everywhere and potentially also the blue background as well.
* improve general readability and order of forms. E.g. smaller font size on dissaggregations, compacter view and presentation. Check the custom GL- forms for some inspiration

**Comment by adrianq** [comment]
Created #50 to tackle your latest comment

**Comment by adrianq** [comment]
The PDF is auto-generated using the associated sections and their dataElements/indicators. The custom form HTML is not used in any way.

Sections are shown, but custom concepts as themes/groups are not. An example:

[JOFM1618 (Swiss Confederation) 2018-04-13.pdf](https://github.com/EyeSeeTea/dataset-configuration/files/1907218/JOFM1618.Swiss.Confederation.2018-04-13.pdf)
