### ISSUE TITLE
Outcome indicators selected on "indicators"

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#44]
One of the requirements discussed initially for outcomes is that a lot of these are sets of three (numerator, denominator and comment). 

What would be best for us is to select the outcome indicator where today there are only data elements . In example: selecting the indicator GL-EB1A: % of enrolled learners who pass the final YEP program exam in stead of having to make sure to select both GL-EB1A-N and -D and -C (numerator, denominator and comment). This would give the app and ux les options and be less prone to user errors.

NB: Some outcomes are also only data elements (e.g. the local ones in countries are usually not indicators with a numerator and denominator and simply a percentage or number entered directly as data element, these still need to be selectable as today). 

Let me know if you have questions ! This might be worth skyping over as well :-)

**Comment by adrianq** [comment]
Outputs -> As it is, just Data Element
Outcome -> 2 Types mixed in the same section => Indicator (Num, Den and Comment)
                                      => Data Elements

**Comment by troyel** [comment]
Two things missing now from data entry form to make it perfect:
1. The indicator result itself should be shown.
2. Is it possible to organise a sub-sections for each outcome result.  Or is this just missing in the metadata to make it happen now? See screenshots below.

Today:
![today.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46fc9b9e229bc1e5cdf9ad4cae58f3806b1c65267107f6737183b471be432d510e5f4eae125a5b15f8fd8839baa47e21d40854b088270a36d43703adbf881eba01b3258f4e85b3bc894bc2fa70.PNG)

How I would like each set of data elements with calculated indicator to look:
![perfect look.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46f89188258780bdcfe5b04caf1fbcd6395428792c07b7692ac7b670bc172300095847fd105e5f15fcf98b78a4b26d748e5d19f1c32f0e2a92624cf5f2d75dad0ba821824584b3bc8349c4e93c21e6828f482c53.PNG)

**Comment by adrianq** [comment]
1 -> @adrianq to look at the customs form approach for this problem
2-> Yes it is about group attribute in the metadata
