### ISSUE TITLE
optimization of save/posting

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#45]
This is probably on the block (and we know early optimization is....) but is it possible to do more bulk posts or larger imports on the save data set? 

* Remember this app can be used on VSAT (high ping) or un-steady internet/power connections from Iraq or Bangui etc.

**Comment by adrianq** [comment]
We have had some preliminary discussions (although as discussed we won't take care of this for the M&E presentation). Yes, there are a lot of calls to the API. You were completely right. In theory, if something fails and you press save again nothing should be duplicated and the dataset should be created properly. We will have to do some extra tests to verify it is working as expected but this is the approach behind the code. I think it is a good first step to deal with this issue but we can discuss more improvements later on

**Comment by troyel** [comment]
just FYI. I created another data set with all indicators now : it took about 250 seconds and did more than 910 requests to the API. I don't think this will be the typical use case - but imagine doing this from a VSAT in the jungle with added 500ms latency to each request.
![all indicators 2 data set.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46e99896638b8dad86eabe57ab4fe3d47b0623723d05e3387591a164fd52690e050a1de853524d41f4aa8c23f7e03b79db0d0ded806d5f76953f15fdbc861ead1da862da11d1e9e1d30695aa2f2ff58a88453f1b041881fa5435a39f4fc85de406.PNG)

**Comment by adrianq** [comment]
Thanks for the analysis. We are already looking into this and we will have some improvements for the next release. Anyway, an optimal solution would probably require a major development (and a discussion with you) but we have some ideas that can reduce this time and calls significantly

**Comment by adrianq** [comment]
@troyel just to keep you posted... We are working on this and it looks like we have a nice solution. We should be able to release a new version by Tuesday/Wednesday next week

**Comment by troyel** [comment]
Fantastic! Looking forward to it! :-)

**Comment by tokland** [comment]
We have done a refactor of the saving process, now we use batched `/metadata` API calls instead of individual model/object endpoints. The number of requests and times have dropped very significantly. We'll release those changes tonight.  On the process we found some bugs with sections metadata, we will report them (the first: https://jira.dhis2.org/browse/DHIS2-2541)

**Comment by troyel** [comment]
Yes fantastic! That makes much more sense :-) Looking forward to it.
