### ISSUE TITLE
Redraw "grey fields" to not scroll horizontally

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#49]
Can we redraw "grey fields" to not scroll horizontally when having impressive amounts of dissaggregations? See picture

**Comment by troyel** [comment]
![grey fields horizontal.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46ef869f3ac285a08ae5bb50e455ff86205c287d3d05af693cc7f33ab0487e021b4d44be44500c41f4a8df2cafe76d768a0d0bedd33e5d70973915adaa9e0dfd50e474d412dcfce9c85ecafa3824e78b854e3b1e06118afb5832a29a4ccf4abb.PNG)

**Comment by troyel** [comment]
How do I open this? accidentially closed it...

**Comment by troyel** [comment]
aha! Drag and drop. (y)

**Comment by adrianq** [comment]
Ok, got it! Let us analyse a bit if it is not particularly difficult and we can take care of it for the M&E presentation. Will keep you posted!
