### ISSUE TITLE
"filter in section" not removed in one location

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#54]

**Comment by troyel** [comment]
![filter in sect bug.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46ee9d96378791e986e7ff50a15ee4d42b5320316546b3397f8fe62bab0021435a571da949090943f5a8d82da6e73c70880f09e980695b75d42103eee9dc4be05ce36ade0d97bcae8b45cae93825e28a8b4e3a16041c80fd4f78.PNG)

**Comment by tokland** [comment]
You are right, we were processing data elements that used <input> tags, but comments (long text) use a textarea. We have broadened the rendering rule so now both types are processed.

![screenshot from 2017-09-12 16-39-26](https://user-images.githubusercontent.com/24643/30331771-f695ead4-97d8-11e7-906d-b4423f08bc78.png)
