### ISSUE TITLE
Horizontal drawing / scrolling back

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#55]
Horizontal drawing seems to be back? I am using incognito...

**Comment by troyel** [comment]
Same data set as previous bug reported..

![horizontal drawing bug.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46e09b882a988ca79be8b303a04ff183204820332b11a4693cc7f33ab0487e021b4d44be44500c41f4a8df2cafe76d768a0d0bedd33e5d70973915adaa9e0dfd50e474d412dcfce9c85ecafa3c2ced8a8a4f3b1f01198eff5e3ca8995985.PNG)

**Comment by tokland** [comment]
You're right, it was disabled, sory, I re-enabled it again. Note that we've done some extra work on this kind of long tables: 1) we show group/DEname only for the first table (if split), and 2) the data element name should tale at most 33% of the viewport, so there is enough space for the values. Check this snapshot:

![screenshot from 2017-09-12 16-21-58](https://user-images.githubusercontent.com/24643/30332019-978bdb60-97d9-11e7-8476-a18c4a106fc3.png)
