### ISSUE TITLE
Active / phased out / inactive indicators (Data Elements)

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#64]
Background:
We introduce changes and updates to out global indicators each year. Depending on how our programmes and measurement approach develops we might want to change som indicators, add new and decommission old ones etc. However - even though we in 2018 will have new indicators we might still need those that are being replaced/removed because some projects that were started in 2017 are still reporting on these into and during parts of 2018. So we need the old indicators to be available but we do not want them to have too much focus because all new projects in 2018 (the majority) should ONLY use the new indicators. So we want some way of giving a lower visual priority to the "phased out indicators".

Suggested solution:
For selecting data elements we need to have some kind of distinction between active indicators, deactivated indicators and indicators that are actively in use, but that are being phased out. 

Currently there is an attribute or group called "Status" where we now have two options. Active and inactive. We want a third option "Phased out" which will mean that these are indicators that CAN be in use - but that are being down-prioritized as we are going to phase them out and only use them for old projects. 

Can we have some way of putting these "PHASED OUT" indicators towards the end of data entry form or giving it a greyed out background or something fitting visually ? I imagine either a collapsed group at the end or a faded grey bacground etc. We can discuss this further on skype.
![Capture2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46cb958a379791acddabf301b44fff9e2c4533317346f67373d0bb29b91522000e594efd41585d17fefdd82fa2b72e6c981e5ab38532022d8c6853beb2901eb70bbb258b4781b4be8d48c7e93d23f5c6.PNG)
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fb2825dde22ee81b7a00595f1fac415a0c46f8a88d2fa7a42062c80d55b98e30063e937f03a6aa8316b500bf20834b87b4bb8e4bc0ef3437aa.PNG)

**Comment by adrianq** [comment]
We would like to add something in Dataset Configuration (a new column in step 4 and by default it is sorted to display the Active Indicators). Inactive indicators will not be displayed. We will first show the active and the phased out will be displayed below

Try to highlight the phased out indicators (darker background, clearly display phase out label?)
