### ISSUE TITLE
Bug when going from selecting away indicators in the sub-sections the "all" tab says it is empty

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/dataset-configuration-blessed#65]
## dhis2

- Username: Troyel.Nerbo
## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
- Platform: Win32
## User report
URL: http://dev.eyeseetea.com:8080/api/apps/dataset-configuration-dhis2-app/index.html#/datasets/add?_k=k4rwhd

Bug when going from selecting away indicators in the sub-sections the "all" tab says it is empty.

![screenshot](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1509442984173152554.png)

**Comment by adrianq** [comment]
Ok, we can now reproduce the error. We will have a look at it
