### ISSUE TITLE
Data Element is selected in more than one section

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/dataset-configuration-blessed#66]
## dhis2

- Username: Troyel.Nerbo
## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
- Platform: Win32
## User report
URL: http://dev.eyeseetea.com:8080/api/apps/dataset-configuration-dhis2-app/index.html#/datasets/add?_k=miplr6

What are these caused by? and how can we fix it?

![screenshot](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1509538545024748171.png)

**Comment by troyel** [comment]
Seems to be a slight bug on the screenshot bug app (couldnt take a proper screenshot of this for some reason, tried multiple times in two sessions).
![bug data element add.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46ea819d638682bd8ea9ba4fa150f59a3d0626772d46ef696097ec22ba416f43554d4ba4125d5715aafe807af7b03c218a5c09bed3690e70c23c03b0aac04ee155e57dd205d0f4ae805ec1ef3724e28b864a3d1701188efc5930b2d4.PNG)

**Comment by adrianq** [comment]
This seems to happen because a Data Element cannot be in more than one section. Basically, if this Data Element is selected two times, as an Output (Data Element) and as an Outcome (Indicator that contains this Data Element). We need to agree on the rule to follow in this case...

**Comment by adrianq** [comment]
@troyel  to double check the metadata
@adrianq to catch the exception and show something like "Talk to your admin re the metadata".

It looks like the same DE is used two times in an indicator. If this is the case we need to validate and just add it once. If the problem is that the same DE is used in two indicator we need to report to Troyel so he can fix the metadata

**Comment by troyel** [comment]
I fixed the metadata on the dev server
