### ISSUE TITLE
Names on outcomes

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#69]
Created a dataset with all indicators in. This has forced forward some errors:

**Comment by troyel** [comment]
![Outcome names.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46c7818e208d8eaccfe7be4ea14eb2d86b56357c2301a03f32dfa17de7412e590e0949a510095944adf98929f5b438218e580affcd7f1d2598694ef1e1c84afd13b0328a488fb7b98b4cc8ed3a2dee83884d3c0c48.PNG)

**Comment by adrianq** [comment]
@troyel I think this is a cache issue. I already saw this, try to give it a try in incognito mode and let us know

**Comment by adrianq** [comment]
@troyel any update on this? Can you confirm this is actually a bug?

**Comment by troyel** [comment]
@adrianq seems to be good now. Regarding cache - is there any way we can force browsers to flush the cache when opening the app for the first time? I foresee some issues here when we deploy and many people will load the pages with the old JS code and not our fancy new one. Perhaps we can implement a test that if the JS is not of the correct versioning according to the app specs it will give a message and instructions to clear cache?

**Comment by tokland** [comment]
> seems to be good now.

Cool!

> Perhaps we can implement a test that if the JS is not of the correct versioning

The caching problem does not affect the custom JS code (as far as we have seen, it always loads the newest version). The problem lies with the HTML of the datasets that data-entry caches. We'll check if there is a workaround for this.
