### ISSUE TITLE
Delay on data entry

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#71]
Adding the ultimate data set forced out some issues: delay on data entry. I'm guessing the JS works in the background and re-draws everything for each change and that gives the big data set a delay for each entry? See gif in comment.

**Comment by troyel** [comment]
![entry delay.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46ed9a8e319bc3ad8ae5be5ae611b2843b492d762a10e17132d0bb2bea1a7a0758561ffd47580e44fcfbda29a2e738748b4e17ff933c0120996048e6edc00db513bb27814e80b7bc8249c9ee3a24ee88875d73.gif)

**Comment by troyel** [comment]
Have you had any time to look into this yet?

**Comment by tokland** [comment]
You are right, Troyel, the entry time for dataset _All 2017 GORS indicators_ is also higher in my machine (~1.5 secs) compared to a "normal" dataset with fewer data elements/indicators, which works fast.

I've tracked down the code until [dhis2.de.updateIndicators](https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-web/dhis-web-dataentry/src/main/webapp/dhis-web-dataentry/javascript/entry.js#L45). The result of an indicator is a mathematical expression to be parsed and evaluated, so it cannot be extremely fast, that explains the times we are experiencing. This dataset has 382 indicators to calculate.

Note that this code is within the dhis2 core, our code does nothing once the forms have been rendered. If we really needed to better support so many indicators, we could check the implementation of that function (maybe it's possible to make it faster, maybe not), but that's core code.

**Comment by troyel** [comment]
Ok - thanks for the quick reply and explanation. We would have had the same issue had we used custom forms with that many indicators than. Great that we have this app then to help us limit the number of indicators.
