### ISSUE TITLE
"expire date" standard value

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#72]
The "expire date" should have standard value 0. I thought this was the field for days for "timely data".  Currently we let people change any data at any time backwards - not ideal across years but within years. 

We would want to have a help text to this explaining that changing it to something else then 0 would make it impossible to change data 15 days after the period end. Potentially we would want to have the option to hide it. If thats not much work in the admin panel?

**Comment by adrianq** [comment]
So let me double check if we fully understand your suggestion:
- Add default 'expiry date' to the admin panel
- Set value by default to 0 for the application although it can be changed in the admin panel
- Add help to 'expiry date' explaining this field in step 2. We want to keep this field in step 2 but with some help explanation
 
Not sure I understand your complaint about changing across years. Are you suggesting to use this field only for days? Not allow negative value?

Is this what you want? It is not difficult we just need to understand what you are suggesting exactly...

**Comment by troyel** [comment]
Hi, apologies for not being very clear on this. 

If I understand the field correctly - it is for days only and cannot have negative values. So if it is monthly reporting and the number of days is set to 31 then reporting on period "January" would close after 1st of March (ish). Currently, we do not close any of the periods - but at some point, we need to start closing down previous years. Say after March next year we would want to start closing periods in 2017. The important thing is that we either want to have 0 as standard or have quite a high number of days starting out - ideally this number would be less to ensure timely reporting. 

Your two points above look good.

**Comment by adrianq** [comment]
Got it!
