### ISSUE TITLE
Negar (local admin) have access issue

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#75]
Hi, tried creating a data set for Negar in Jordan. Her user got this issue when trying to save the data set: 

on:
http://dev.eyeseetea.com:8080/api/26/sharing?type=categoryCombo&id=nC0WHgkV41l&mergeMode=MERGE
![Negar.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46c6919d2290c1e5cdf9ad4cae58f3806b1c65267107f6737183b471be432d510e5f4eae125a5b15f8fd8839baa47e21d40854b088270a36d43703adbf881eba00bb288c4d8cb7bf8e4ec9fa70.PNG)

**Comment by troyel** [comment]
You can test with "Negar.Ghobadi" password "Testing123"

**Comment by tokland** [comment]
We'll look into it, a 403 means the user cannot perform the operation, but probably the saving should continue.

**Comment by tokland** [comment]
Here we were still using the old saving process, closing in favour of #76
