### ISSUE TITLE
What should we do when a user cannot change an associated userRole?

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dataset-configuration-blessed#76]
If you try to create a dataset having core competency EDUCATION, we get this error:

```
"message": "User `Negar Ghobadi [RZmzKVc9ToB] (User)` is not allowed to update object `JO__dataset_education [lo7nrPmQ32N] (UserAuthorityGroup)`.",
                            "mainKlass": "org.hisp.dhis.user.UserAuthorityGroup",
                            "errorCode": "E3001"
```

Is this a normal scenario? it's ok to show this error or a user should be able to create datasets without rights on the associated user roles?

**Comment by tokland** [comment]
@troyel: Any update on this? It's related to #78

**Comment by troyel** [comment]
Hi - I think the user should have edit rights on the role. The alternative route on this would be to go for creating new roles for each data set and putting these on users & or user groups.

**Comment by troyel** [comment]
Hi - I have updated the user roles and JO_Administrator (where Negar is part of) has rw- rights to Education (and all other roles). However - this error still comes. Just tried a basic Educaiton data set: Error messaage:


Global Ouput and Outcome Reporting (latest)
Search apps

N G
1
Initial configuration
2
General information
3
Organisation unit
4
Sections
5
Disaggregation
6
Grey fields
7
Sharing
8
Save
Dataset could not be saved
Error: POST metadata error:
{
    "importParams": {
        "importMode": "COMMIT",
        "identifier": "UID",
        "preheatMode": "REFERENCE",
        "importStrategy": "CREATE_AND_UPDATE",
        "atomicMode": "ALL",
        "mergeMode": "MERGE",
        "flushMode": "AUTO",
        "skipSharing": false,
        "skipValidation": false,
        "username": "Negar.Ghobadi"
    },
    "status": "ERROR",
    "stats": {
        "created": 0,
        "updated": 0,
        "deleted": 0,
        "ignored": 5,
        "total": 5
    },
    "typeReports": [
        {
            "klass": "org.hisp.dhis.dataelement.DataElementCategoryOption",
            "stats": {
                "created": 0,
                "updated": 0,
                "deleted": 0,
                "ignored": 2,
                "total": 2
            },
            "objectReports": [
                {
                    "klass": "org.hisp.dhis.dataelement.DataElementCategoryOption",
                    "index": 0,
                    "errorReports": [
                        {
                            "message": "Invalid reference [M9dPUWRdk4L] (UserGroup) on object JOFM1704 (NMFA) [N9kIYBVgnwe] (DataElementCategoryOption) for association `userGroupAccesses`.",
                            "mainKlass": "org.hisp.dhis.dataelement.DataElementCategoryOption",
                            "errorCode": "E5002"
                        }
                    ]
                }
            ]
        },
        {
            "klass": "org.hisp.dhis.user.UserAuthorityGroup",
            "stats": {
                "created": 0,
                "updated": 0,
                "deleted": 0,
                "ignored": 2,
                "total": 2
            },
            "objectReports": [
                {
                    "klass": "org.hisp.dhis.user.UserAuthorityGroup",
                    "index": 0,
                    "errorReports": [
                        {
                            "message": "Invalid reference [M9dPUWRdk4L] (UserGroup) on object JO__dataset_education [lo7nrPmQ32N] (UserAuthorityGroup) for association `userGroupAccesses`.",
                            "mainKlass": "org.hisp.dhis.user.UserAuthorityGroup",
                            "errorCode": "E5002"
                        }
                    ]
                }
            ]
        },
        {
            "klass": "org.hisp.dhis.dataset.DataSet",
            "stats": {
                "created": 0,
                "updated": 0,
                "deleted": 0,
                "ignored": 1,
                "total": 1
            }
        }
    ]
}

← PREVIOUS

NEXT →

CANCEL

SAVE
Send Feedback
