### ISSUE TITLE
Add locations to pre-save message

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/dataset-configuration-blessed#77]
## dhis2

- Username: Troyel.Nerbo
## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
- Platform: Win32
## User report
URL: http://dev.eyeseetea.com:8080/api/apps/dataset-configuration-dhis2-app/index.html#/datasets/add?_k=jtuahz

Hi - can we add also info on the locations where this data set is added? Thanks!

![screenshot](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1512481451393523410.png)

**Comment by tokland** [comment]
> can we add also info on the locations where this data set is added?

Sure, but what do you mean by "locations"? the user roles?

**Comment by troyel** [comment]
By locations I mean the org units where the data set is allocated.

**Comment by tokland** [comment]
Ok, no problem.
