### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#78]
Error on save for user "Laurence.Hargreaves" 

Global Ouput and Outcome Reporting (latest)
Search apps

L H
1
Initial configuration
2
General information
3
Organisation unit
4
Sections
5
Disaggregation
6
Grey fields
7
Sharing
8
Save
Dataset could not be saved
Error: POST metadata error:
{
    "importParams": {
        "importMode": "COMMIT",
        "identifier": "UID",
        "preheatMode": "REFERENCE",
        "importStrategy": "CREATE_AND_UPDATE",
        "atomicMode": "ALL",
        "mergeMode": "MERGE",
        "flushMode": "AUTO",
        "skipSharing": false,
        "skipValidation": false,
        "username": "Laurence.Hargreaves"
    },
    "status": "ERROR",
    "stats": {
        "created": 0,
        "updated": 0,
        "deleted": 0,
        "ignored": 8,
        "total": 8
    },
    "typeReports": [
        {
            "klass": "org.hisp.dhis.dataelement.DataElementCategoryOption",
            "stats": {
                "created": 0,
                "updated": 0,
                "deleted": 0,
                "ignored": 2,
                "total": 2
            },
            "objectReports": [
                {
                    "klass": "org.hisp.dhis.dataelement.DataElementCategoryOption",
                    "index": 0,
                    "errorReports": [
                        {
                            "message": "Invalid reference [p33Zkz7FTNz] (UserGroup) on object IRFM1604 (ECHO) [B6NiLeAsDEG] (DataElementCategoryOption) for association `userGroupAccesses`.",
                            "mainKlass": "org.hisp.dhis.dataelement.DataElementCategoryOption",
                            "errorCode": "E5002"
                        }
                    ]
                }
            ]
        },
        {
            "klass": "org.hisp.dhis.user.UserAuthorityGroup",
            "stats": {
                "created": 0,
                "updated": 0,
                "deleted": 0,
                "ignored": 5,
                "total": 5
            },
            "objectReports": [
                {
                    "klass": "org.hisp.dhis.user.UserAuthorityGroup",
                    "index": 0,
                    "errorReports": [
                        {
                            "message": "Invalid reference [M9dPUWRdk4L] (UserGroup) on object IR__dataset_education [OmBrQvjfoFD] (UserAuthorityGroup) for association `userGroupAccesses`.",
                            "mainKlass": "org.hisp.dhis.user.UserAuthorityGroup",
                            "errorCode": "E5002"
                        }
                    ]
                },
                {
                    "klass": "org.hisp.dhis.user.UserAuthorityGroup",
                    "index": 2,
                    "errorReports": [
                        {
                            "message": "Invalid reference [M9dPUWRdk4L] (UserGroup) on object IR__dataset_shelter [nPS9EGS7bBI] (UserAuthorityGroup) for association `userGroupAccesses`.",
                            "mainKlass": "org.hisp.dhis.user.UserAuthorityGroup",
                            "errorCode": "E5002"
                        }
                    ]
                },
                {
                    "klass": "org.hisp.dhis.user.UserAuthorityGroup",
                    "index": 3,
                    "errorReports": [
                        {
                            "message": "Invalid reference [M9dPUWRdk4L] (UserGroup) on object IR__dataset_wash [IwXJbBuPEXb] (UserAuthorityGroup) for association `userGroupAccesses`.",
                            "mainKlass": "org.hisp.dhis.user.UserAuthorityGroup",
                            "errorCode": "E5002"
                        }
                    ]
                }
            ]
        },
        {
            "klass": "org.hisp.dhis.dataset.DataSet",
            "stats": {
                "created": 0,
                "updated": 0,
                "deleted": 0,
                "ignored": 1,
                "total": 1
            }
        }
    ]
}

← PREVIOUS

NEXT →

CANCEL

SAVE
Send Feedback

**Comment by tokland** [comment]
Let's see, the two user groups mentioned in the JSON response are [these](http://dev.eyeseetea.com:8080/api/userGroups.json?paging=false&filter=id:in:[p33Zkz7FTNz,M9dPUWRdk4L]):

```
{
    userGroups: [{
        id: "p33Zkz7FTNz",
        displayName: "AsiaEurope_Users"
    }, {
        id: "M9dPUWRdk4L",
        displayName: "GL_GlobalAdministrator"
    }]
}
```

- _AsiaEurope_Users_: The problem is that this user cannot update the project (category option) _IRFM1604 (ECHO)_. Note: We update the associated project to add the organisation units in the dataset.
- _GL_GlobalAdministrator_: The problem is that this user cannot update the user roles shown (_IR__dataset_education, IR__dataset_shelter, IR__dataset_wash_). Note: We add the dataset being created/edited to _COUNTRY__dataset_CORECOMPETENCY_ user roles.

Troyel, what should we do? continue with the saving and add warnings in the message to the admins? or should this user have rights to do these operations?

**Comment by troyel** [comment]
I think the main important things are to: a. map which authorities and sharing rights that the user needs to have to use all the functions we want them to in the app. And b) to make some more sensible error messages so that any potential user rights gaps can be adressed. I'm not sure if we can continue the save and then later fix the errors here or if it is better to catch these earlier and stop the process OR go ahead with the saving and have to patch it up later. I would preffer fixing it before the save. Does that make sense?

**Comment by tokland** [comment]
Regarding those errors with the two userGroups, we have checked it more deeply. The problem arises when we are trying to update a project (categoryOption) -note that the same would happen when saving a userRole- that has already assigned private user groups. Once we set them as sharing-publicAccess = "read", it works. Troyel, is it ok to set those user groups as public readable? this would be by far the easiest solution.

**Comment by adrianq** [comment]
Note that those errors when we try to update a project have to do with some bugs in Dhis2. We could maybe find a workaround but it would require a few more calls to the API (that could turn into several calls if many Org Units and Core Competencies are chosen). We can go into the specifics if this ends up being a hard requirement...

**Comment by tokland** [comment]
Mapping of action/permissions:

1. Add the dataset to the associated user roles. The user should belong to this user role for this to succeed. We could check at the start and only show these core competencies (associated to the user role). 

    [ISO_COUNTRY_Step7]\_\_dataset_[CORECOMPETENCY]

2. Sharings for the dataset:

   [ISO_COUNTRY_Step7]_Users -> Read
   [ISO_COUNTRY_Step7]_Administration -> Write

3. If there is an associated project, add Org Units to the Project (Category Options) -> That's ok as far as all user groups sharing of the project (categoryOptions) are public-read. See the previous comment for more details.

4. Add sharing to category combos:
    [ISO_COUNTRY]_Users -> again, we need read permission.
