### ISSUE TITLE
Some user roles seems not to match the core competencies

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#81]
See for instance:
![screenshot from 2017-12-19 10-32-31](https://user-images.githubusercontent.com/6850223/34152939-2dd8a5a6-e4a8-11e7-89d8-083119f14b34.png)

![screenshot from 2017-12-19 10-32-56](https://user-images.githubusercontent.com/6850223/34152947-3518ac6c-e4a8-11e7-953c-0ba770b4a828.png)

The way we calculate the user role is JO__dataset_[corecompetency_withoutspaces_lowercase] We  use this use role to add the new data set (on save). If they don't match we won't be able to add the data set to the user role

**Comment by troyel** [comment]
Will get back to this. I have revised a little the CC list. removed GBV and Finance/PCM as these should not be there. Renamed the other group and harmonized them to MULTIPURPOSE CASH/OTHER. Would tris try to match JO__dataset_multipurposecash/other ?

**Comment by tokland** [comment]
The data element / indicator core competencies are now synced expect for _FINANCE/PCM_, which still exist as indicator group in Core Competency/Area, I guess it should be deleted. 

As for the user role, the name removes all non-alphanumerical chars, so the slash would be removed: `JO__dataset_multipurposecashother`. 

Those two metadata should match:

![1](https://user-images.githubusercontent.com/24643/34557565-f5f6635e-f13a-11e7-997d-d19223abe629.png)

![2](https://user-images.githubusercontent.com/24643/34557567-f85926cc-f13a-11e7-8e2d-0772ecac36fa.png)

**Comment by troyel** [comment]
Does the AF__dataset_foodsec work for Food Security or should I rename them?

**Comment by adrianq** [comment]
You should rename it as Food Security will turn into the user role AF__dataset_foodsecurity. The rule is that to create the user role name we remove all non-alphanumerical chars and make it lower case.

**Comment by tokland** [comment]
DB imported (20180110T032602Z). User role match with core competency.  Not critical, but note that "FINANCE/PCM" still exists as indicator group set: http://dev.eyeseetea.com:8080/dhis-web-maintenance/#/edit/indicatorSection/indicatorGroupSet/ScGREGTV6JI

**Comment by troyel** [comment]
Fixed. Thanks!
