### ISSUE TITLE
Other for Data Elements and Indicators has a different name

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#82]
Currently, Core Competency Other Name doesn't match between Indicator Group and Data Element Group.

Indicator Group-> OTHER ACTIVITIES
Data Element Group->OTHER/SHARED ACTIVITIES

This makes Other outcomes empty as no indicators are found.

**Comment by troyel** [comment]
Updated. Should be current on tomorrows DB.
