### ISSUE TITLE
Hide country sharing step 7

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#83]
I think we can hide the country sharing step (Step 7) as this seems t obe only a next-click in all my tests currently. 

Alternatively : only show it if it does not give a matching country. - Waht do you think?

**Comment by adrianq** [comment]
For the record, we will hide step 7 if a project has been selected and this project has a country assigned.  What we used to do was to pre-filled step 7 but now we will just hide step 7.
