### ISSUE TITLE
"Expiry days" in step 2 should be hidden

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#84]
"Expiry days" in step 2 needs to have a different explanation and I think we want to hide this in the beginning. Can we have a button/user rights to show the field and not? 

New explanation: "(How many days after the period before the data set is locked for changing data. Example: 5 means: after February 5th it is not possible to make changes to January anymore. 0 is no lock.)

**Comment by adrianq** [comment]
Sorry @troyel forgot to discuss this at our meeting today.  Do you mean we should display the expiry days for admin users? users that belong to GL_GlobalAdministrator usergroups?

**Comment by tokland** [comment]
@troyel I am ready to tackle this issue. By having "user rights" you mean being super admin (_ALL_ authority) or belonging to GL_GlobalAdministrator?

**Comment by troyel** [comment]
I mean by having a separate user group with kind of power app users. This could be the GL_GlobalAdministrator for now - but should probably be a different group so great if not hard coded.

**Comment by adrianq** [comment]
Ok,  got it! We will add the admin group as a setting so it can be changed in the future. Keep in mind that settings will only be available for users with authority ALL.

**Comment by troyel** [comment]
authority all meaning being sys/superadmin? Not possible to link it all to a group or role separate from sys-admin?

**Comment by tokland** [comment]
> authority all meaning being sys/superadmin?

The authority _ALL_ exists as a normal authority, assignable to a user role. De facto having this authority makes the user a superadmin, yes. See for example:

http://dev.eyeseetea.com:8080/dhis-web-maintenance-user/showUpdateRoleForm.action?id=2332

> Not possible to link it all to a group or role separate from sys-admin?

Only if we hardcoded group names or roles (as there is no "sharing" concept for apps), this we wanted to avoid. Custom authorities cannot be created either. As we have done in other projects, we have used the existing authority _M_dhis-web-maintenance-appmanager_ for this, so users with authorities _ALL_ or _M_dhis-web-maintenance-appmanager_ (through a user role) are allowed to change settings (expiry date will be visible for them). Is this be enough?

**Comment by tokland** [comment]
Finally, it's implemented like this:

- When an admin user first access the app, a role named "DataSet Configuration admin" with authorities "See DataSet Configuration" and "M_dhis-web-maintenance-appmanager" is created.
- Users with this user role can:
  - Access settings (clicking the settings button )
  - See expiry date field on step "General Information"
