### ISSUE TITLE
CSS table header tweaks

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#89]
I have added some longer category names now - is it possible to see if we can tweak the tables a little to be a bit more flexible in the drawing of the table headers? See example.

![2018 indicators test.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46bac4cb7bc28aa78be0bc42b052e287695222603d46ef696097ec22ba416f43554d4ba4125d5715aafe807af7b03c218a5c09bed3690e70c23c03b0aac04ee155e57dd205d0f4ae805ec1e13724e28a8c4838170c1f8ffb5a36b2d4.PNG)

**Comment by tokland** [comment]
https://github.com/EyeSeeTea/dataset-configuration/pull/222
