### ISSUE TITLE
Fix sharing issue permissions

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#91]
- [x] Create user group for all dataset configuration users
- [ ] Modify sharing settings for all relevant user groups to add this new user group with read permission. Relevant user groups identified so far are:
   - [x] GL_GlobalAdministrator
   - [x] MERO_users

**Comment by troyel** [comment]
I'll send a new database after update tonight- new group will be:

Name:
GL_DataSetConfiguratorApp_users
ID:
JWDNMfp2Mz6

**Comment by tokland** [comment]
The newly imported DB does not have this group _GL_DataSetConfiguratorApp_users_ (it does exist in latestgors.nrc.no, though), maybe the DB dump is previous to the user group creation? 

By the way, not all 4 users you sent us to test belong to this group (only two) in latestgors, should we add them?

**Comment by tokland** [comment]
Newly imported DB, not it exists (assigned to 6 users):

http://dev.eyeseetea.com:8080/dhis-web-maintenance-user/editUserGroupForm.action?userGroupId=621144

GL_GlobalAdministrator and  meroUSERS have GL_DataSetConfiguratorApp_users have as read-sharing, that's correct
