### ISSUE TITLE
Tried deploying on latest

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#93]
Hia, I tried deploying the app on latestgors.nrc.no which is the daily copy of production, meta-data wise I think it was only missing the theme indicator group set which I added- but it got stuck here:
![datasetconfig 71 latestgors.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46ec958e229186bd8ce6b145ad5ab0c378062b723d01b03f778af13bfd0e39111d0014f9121c4d4eeefc8178a3be6d268d555abcd76d0e74c63f42aebcd31bbb00a83c990dd4e8e8d51199a26867f5819d4e3614041d88fb5432a49d4ecc5df64df300.PNG)

**Comment by tokland** [comment]
@troyel could you send us by email the database dump to check the metadata?

**Comment by tokland** [comment]
I've identified the problem: when rendering grey fields for data elements in the category combo "CashType/Displacement/Sex", the component could not get its categoryOptionCombos. I checked this CC in the API (https://SERVER/api/categoryCombos/i8QPbiFNB2d.json), and indeed, that field was an empty array:

http://download.zaudera.com/public/i8QPbiFNB2d.json

I then re-saved the CC (some change is needed to force a re-save, like a change of the name) and now the categoryOptionCombos are there as usual:

http://download.zaudera.com/public/i8QPbiFNB2d-postsave.json

And now the grey fields render fine.  Any idea why would this CC lack its COCs? This should not happen, but somehow it did, so I'll make a minor change in our code so it does not fail (it will just render no checkbox, which will serve as a signal that something is wrong with the CC).

(cc @adrianq)

**Comment by tokland** [comment]
This same problem is present in 7 more category Combos:

```
$ curl -sS -u "USER:PASSWORD" "https://SERVER/api/categoryCombos.json?fields=id,name,categoryOptionCombos[id]&paging=false" | jq -r '.categoryCombos[] | select(.categoryOptionCombos | length == 0) |.name
Cash Type
Cash Type / Head of Household
Construction Type (2018)
Infrastructure Type
Sanitation NFI (WASH)
Shelter Contribution Type
Water NFI (WASH)
```

**Comment by troyel** [comment]
Hum - might be I need to generate resource table. Will send new DB dump tomorrow - lets see if we have the same issue.

**Comment by tokland** [comment]
The DB dump still has the missing cocs, but running this maintenance task is enough: Data Administration -> Maintenance -> Update category option combinations -> [Perform maintenance]

![3](https://user-images.githubusercontent.com/24643/34558830-dee1d22a-f13f-11e7-8481-e9b45c064ec8.png)
