### ISSUE TITLE
Theme for outcomes

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#94]
How do we get themes for outcomes? Do we need to create an equivalent indicator group for Theme as in data elements or is this something that is ruled by the data element allocations?

**Comment by tokland** [comment]
> Do we need to create an equivalent indicator group for Theme as in data elements or is this something that is ruled by the data element allocations?

The first option: we need an indicatorGroupSet (Theme), indicatorGroups for this set and indicators assigned to them. I see we already have Theme -> Permanent Shelter (with GL-SB2A/PM assigned) on dev.
