### ISSUE TITLE
Warning on a lot of outcomes

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#95]
Given the very slow forms when a lot of indicators are selected - can we implement a warning if a number of indicators over say 20 are added with an explanation that the form slows down? I'm not sure if 20 is the sweetspot of where it becomes slow or if it can be 30 - but anyhow some warning would be good.

**Comment by tokland** [comment]
Ok, we'll discuss it the next dev meeting and get back to you.

**Comment by troyel** [comment]
I think perhaps having a warning at 10 outcomes would be enough.

**Comment by adrianq** [comment]
We want to have a look first at the performance issues and depending on that w ewill show a warning message

**Comment by troyel** [comment]
I did a quick test on the vanilla forms. I think there are potentially two/three intermediate solutions here : 
1.  Add a warning and
2. remove the indicator itself from showing in the forms if there is sufficiently many. E.g. if someone wants to add all possible variants it is currently entierly unsuable. But then removing the calculated value would solve the issue on the performance side. Or

3. I don't know if it is possible to disable the auto-calculation part of the JS on large data sets and then implement a always visible header button or something to run it for when you want to see the results?
