### ISSUE TITLE
Camp management new indicators issue

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#96]
Just created a Camp management only data set with the new indicators I am implementing. The form doesn't seem to draw correctly in incognito mode.. Does it look like this on your end as well?
![draw issue.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46ec869b34c28aba9cfcba01e81fe086264c22703d46f96925dde07de7437d56560e1faa41095f44feaa8b2ff7b23871984019af80330b2b9b645bf9fa9015ad00b22a8a4a84b3bc8d4ec7e13f2ce1839d02.PNG)

**Comment by tokland** [comment]
My fault, the custom JS code was not in the newly imported DB. Done.

(That's how it looks without no processing at all)
